##########################################################################
#
# 用户微服务
# web访问端口号 约定：8003
#
##########################################################################
server:
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  #tomcat默认为2M 超过2M的文件不会被捕获，需要调整此处大小为-1

##########################################################################
#
# 配置项目信息
#
##########################################################################
spring:
  application:
    name: service-files
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 512000 #请求的文件大小限制为500Kb
      max-request-size: 512000
  profiles:
    active: dev #yml 中配置文件的环境配置，dev开发环境，test测试环境，prod生产环境

##########################################################################
#
# fastdfs的配置信息
#
##########################################################################
fdfs:
  #连接时间
  connect-timeout: 30
  #读取时间
  so-timeout: 30
  # tracke服务的地址
  tracker-list: 192.168.1.155:3333
