##########################################################################
#
# 文章微服务
# web访问端口号 约定：8001
#
##########################################################################
server:
#  port: 8001
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: -1  #tomcat默认为2M 超过2M的文件不会被捕获，需要调整此处大小为-1

##########################################################################
#
# 配置项目信息
#
##########################################################################
spring:
  application:
    name: service-user
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  profiles:
    active: dev #yml 中配置文件的环境配置，dev开发环境，test测试环境，prod生产环境
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/imooc-news-dev?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8


#mybatis-plus 配置
mybatis-plus:
  type-aliases-package: com.gegeda.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

